image:
  file: .gitpod.Dockerfile

tasks:
  - name: Terminal 1
    before: printf 'export PATH="%s:$PATH"\n' "~/.local/bin" >> $HOME/.bashrc && exit
    init: pip3 install pylint
    command: |
      source ~/.bashrc
      python -m http.server 8000
      clear
  - name: Open webserver in terminal 2
    command: python -m http.server 8000
vscode:
  extensions:
    - ms-python.python
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-browser